### ISSUE TITLE
New Typescript projects created with the CLI do not build correctly

### ISSUE THREAD

**Issue by bartolkaruza** [emin93/react-native-template-typescript#24] opened 2019-01-09 12:27 UTC
Moved here from an issue posted on React Native core: https://github.com/facebook/react-native/issues/22914

The run-android part, is covered on this react-native-cli issue https://github.com/react-native-community/react-native-cli/issues/65

Maybe you could have a look at point 1 of that RN issue regarding the generated project using this template?

**Comment by emin93** [comment] 2019-01-11 15:45
Thanks for the issue. Right now I really can't find the time to have a deeper look but I quickly read through the issues to find out what this is about.

What I can say so far:
Since RN 0.57 and Babel 7 this template doesn't do much because TypeScript is supported out of the box. The building part is being handled by Babel and the RN CLI afaik.

The only thing this template does now is adding type definitions for React & RN, replacing the App.jsx with the App.tsx, adding a .tsconfig file which is only being used to do type checking and removing obsolete files like `.flowconfig`. All of those things don't affect the building process, at least not in a way they would cause the error in the other issue.

Does anyone else have the same issue? Could someone have a deeper look at this?

**Comment by buncismamen** [comment] 2019-02-05 08:06
I just create new project wiht this and it have `App.js` and `App.tsx`

**Comment by emin93** [comment] 2019-02-21 12:43
Hi @bartolkaruza,

So I took the time and tried to reproduce the issue but I couldn't. `tsc` works and also building and deploying to an Android device including live reload.

Therefore I'm going to close this issue. If you think this is wrong and I should reopen it, I'd be happy if you could create a sample repository where this issue occurs, so I can check it out and see what's going on.

**Closed by emin93** 2019-02-21 12:43 UTC
Labels: bug

**Comment by bartolkaruza** [comment] 2019-02-22 01:48
Thank you for taking the time @emin93, I really appreciate it. The original issue was not mine, so I wouldn't be able to even tell you if this is still a problem. 
OP: @Sean-Brown-Digi

**Comment by Maxwell2022** [comment] 2019-02-27 06:13
I can reproduce it with a starter project:

```shell
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.58.5
$ react-native init testApp --template typescript
$ cd testApp
$ ./node_modules/.bin/tsc
```

```
setup.js:1:1 - error TS1208: Cannot compile namespaces when the '--isolatedModules' flag is provided.

1 const fs = require('fs')
  ~~~~~


Found 1 error.
```

**Comment by emin93** [comment] 2019-02-27 07:36
Please execute the setup.js post installation script first after creating the project. This should fix the issue for you. Note that this is just a one time execution (see Readme file for detailed explanation).

With the next React Native version, the CLI will allow this to happen automatically, so you don't need to execute the setup.js manually anymore.

**Comment by Sean-Brown-Digi** [comment] 2019-02-27 13:56
Ah ok that was my issue, I didn't know you had to run a post installation script, though that makes me wonder why the CLI doesn't just run this script automatically when it creates the project?

**Comment by emin93** [comment] 2019-03-01 13:39
@Sean-Brown-Digi In that case, please check out the `README.md` file. Unfortunately the React Native CLI doesn't allow automatic execution of post installation scripts but that will change in the near future. As soon as they enable that, the script will be executed automatically.
