### ISSUE TITLE
Cannot find module '@babel/plugin-external-helpers'

### ISSUE THREAD

**Issue by sinewave440hz** [emin93/react-native-template-typescript#21] opened 2018-09-20 12:13 UTC
Thank you so much for this great template, it has simplified my life :)

## Expected results

Running app after following readme.

## Observed results

RSoD showing error:
Cannot find module '@babel/plugin-external-helpers'

Installing said module fixes the problem!

**Comment by emin93** [comment] 2018-09-20 12:55
Hi @sinewave440hz, I'm glad you're enjoying the template 😃

May I ask if this error also happens when you set up a project without TypeScript? (`react-native init MyApp`)

**Comment by sinewave440hz** [comment] 2018-09-20 13:52
I can confirm that no, the error does not happen in a "plain" init project...

**Comment by emin93** [comment] 2018-09-20 14:30
The error gets shown in a red screen right after the app starts?

To give you a bit of insight: Starting with React Native 0.57 this template only adds type definitions and `tsc` for the type checking part. This means the error you have should also happen in a new project without TypeScript because this template doesn't change anything regarding transpilation. I use this template myself pretty much every week and I've never encountered that issue.

![screen shot 2018-09-20 at 16 30 07](https://user-images.githubusercontent.com/5310475/45825393-75d80900-bcf2-11e8-8369-aac1b38b9291.png)

**Comment by emin93** [comment] 2018-09-20 14:34
I just did some further research and it seems other people have the same issue as well without TypeScript: https://stackoverflow.com/questions/52415404/react-native-init-0-57-cannot-find-module-babel-plugin-external-helpers

Seems like it's an issue in the `metro-react-native-babel-preset` package, which has been fixed in `0.45.5`. Can you try to update the `metro-react-native-babel-preset` package to the latest version and try again?

**Comment by sinewave440hz** [comment] 2018-09-20 17:59
I tried just before leaving work and using your template worked. I was scratching my head over it on the way home, but I just saw (in the SO link you posted) that in between when I first reported this and the last install, the RN people went in and fixed it :D Let’s shut this issue down! Obviously explains why it worked for you previously to and earlier today...

**Comment by emin93** [comment] 2018-09-21 06:52
Haha, yes. I have to admit, always using latest dependencies can complicate things. But I'm glad the issue is solved now.

**Closed by emin93** 2018-09-21 06:52 UTC
Labels: bug
