### ISSUE TITLE
Tests fails with RN 0.59

### ISSUE THREAD

**Issue by victorlevasseur** [emin93/react-native-template-typescript#37] opened 2019-04-12 08:50 UTC
If a test has the tsx extension and contains JSX code, the tests fails with this error message : 
```
Jest encountered an unexpected token
```

However, if the tests does not contain JSX, it works perfectly.

**Comment by victorlevasseur** [comment] 2019-04-12 08:54
However, with this configuration, it works perfectly:

```
module.exports = {
  "preset": "react-native",
  "moduleDirectories": [
    "node_modules",
    "src"
  ],
  "transform": {
    "^.+\\.ts?$": "ts-jest",
    "^.+\\.tsx?$": "ts-jest",
    "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
  },
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "jsx",
    "json",
    "node"
  ],
  "moduleNameMapper": {
    "^.+\\.(css|less|scss)$": "identity-obj-proxy"
  },
  "transformIgnorePatterns": []
}
```

**Comment by emin93** [comment] 2019-04-15 04:19
Hi @victorlevasseur,

Thanks for creating the issue. Unfortunately I cannot reproduce the issue. Which version of React Native are you using? Is there a `jest.config.js` in your project folder?

Try creating a new project (`react-native init MyApp --template typescript`) and please check if the issue also happens there. If it doesn't, try to find out what's the difference to your project.

**Comment by emin93** [comment] 2019-04-16 06:39
I'll close this issue for now. Let me know if you think it should be re-opened.

**Closed by emin93** 2019-04-16 06:39 UTC
Labels: question
